# Generated by Django 4.1.3 on 2023-03-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='adventure_type',
            field=models.CharField(choices=[('1', 'Hiking'), ('2', 'Climbing'), ('3', 'Caving')], default='1', max_length=50),
        ),
    ]
